name: '[E2E] Tests'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    strategy:
      fail-fast: false
      matrix:
        test-file: 
          - "main-ad-area-visible.spec.ts"
          - "my-discount-client.spec.ts" 
          - "theme-discount-visible.spec.ts"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup E2E environment
        uses: ./.github/actions/setup-e2e

      - name: Run E2E test - ${{ matrix.test-file }}
        run: npx playwright test e2e/${{ matrix.test-file }} --reporter=line
        env:
          NODE_ENV: test
          NEXT_PUBLIC_ENV: test
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.test-file }}
          path: e2e-output/
          retention-days: 7

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-${{ matrix.test-file }}
          path: e2e-output/coverage/
          retention-days: 7